# Generated by Django 4.0.2 on 2022-02-13 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[], default='Non selected', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='projectreport',
            unique_together={('project', 'user_reported', 'report_date')},
        ),
    ]
