# Generated by Django 4.0.2 on 2022-02-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category_alter_projectreport_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
