# Generated by Django 4.0.2 on 2022-02-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='average_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_fund',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='reports_count',
            field=models.IntegerField(default=0),
        ),
    ]
