# Generated by Django 4.0.2 on 2022-02-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_average_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
    ]
