# Generated by Django 4.0.2 on 2022-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.IntegerField(),
        ),
    ]
