# Generated by Django 4.0.2 on 2022-02-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_category'),
        ('projects', '0008_alter_project_category'),
    ]

    operations = [
    ]
