# Generated by Django 4.0.2 on 2022-02-15 03:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to=users.models.image_upload)),
                ('birth_date', models.DateField()),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
