# Generated by Django 4.0.2 on 2022-02-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
